# All platforms listed in alphabetic order

platforms += loongson64
platforms += loongson32
platform-$(CONFIG_MACH_MEGASOC)     += megasoc/

# include the platform specific files
include $(patsubst %, $(srctree)/arch/loongarch/%/Platform, $(platforms))
